### PR TITLE
ENH(TST): rudimentary possible skeleton for testing __main__ functionality

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by yarikoptic** [comment]
ho ho -- with the first fruit from the added testing ;)

**Comment by yarikoptic** [comment]
oh well -- it keeps bringing.  since all the commands do work in command line, I guess it is side-effect of having stdout as StringIO. blindly swapping it to BytesIO flips what fails.
I might get back to it later to get to the bottom of it, meanwhile -- here it is as an idea to pursue ;)

**Comment by yarikoptic** [comment]
<details>
<summary>FWIW, adding imports of unicode_literals </summary>

```patch
$> git show
commit ed06dc504340da052d5a3703cfd4c80058c6d01d (HEAD -> enh-coverage)
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Fri Apr 5 11:30:51 2019 -0400

    BF(?): add import of unicode_literals in a few spots for uniform strings handling as unicode
    
    Resolves failing test__main__ tests

diff --git a/elasticluster/__main__.py b/elasticluster/__main__.py
index 484dec6..0055b10 100755
--- a/elasticluster/__main__.py
+++ b/elasticluster/__main__.py
@@ -18,6 +18,7 @@
 
 from __future__ import print_function
 from __future__ import absolute_import
+from __future__ import unicode_literals
 from builtins import str
 
 # stdlib imports
diff --git a/elasticluster/conf.py b/elasticluster/conf.py
index 24ab4ab..691b8cf 100755
--- a/elasticluster/conf.py
+++ b/elasticluster/conf.py
@@ -32,7 +32,7 @@ rest of ElastiCluster happens in three stages:
 3. Instanciate the actual working objects.
 """
 
-from __future__ import (print_function, division, absolute_import)
+from __future__ import (print_function, division, absolute_import, unicode_literals)
 
 # compatibility imports
 from future import standard_library
diff --git a/elasticluster/subcommands.py b/elasticluster/subcommands.py
index 2ee763b..1ff03f1 100755
--- a/elasticluster/subcommands.py
+++ b/elasticluster/subcommands.py
@@ -15,7 +15,7 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
-from __future__ import print_function
+from __future__ import print_function, unicode_literals
 
 # compatibility imports
 from future.utils import with_metaclass
```
</details>

addresses that failure 

<details>
<summary>but causes others:</summary>

```
=========================================================== FAILURES ============================================================
_____________________________________________________ test_gce_accelerator1 _____________________________________________________
tests/test_conf.py:85: in test_gce_accelerator1
    cluster = creator.create_cluster('example_google')
elasticluster/conf.py:1032: in create_cluster
    .format(template=template))
E   ConfigurationError: No cluster template configuration by the name `example_google`
------------------------------------------------------- Captured log call -------------------------------------------------------
conf.py                    773 ERROR    In section `cluster/example_google`: Key 'nodes' error:
Missing key: <type 'str'>
conf.py                    777 ERROR    Dropping configuration section `cluster/example_google` because of the above errors
_____________________________________________________ test_gce_accelerator2 _____________________________________________________
tests/test_conf.py:125: in test_gce_accelerator2
    cluster = creator.create_cluster('test')
elasticluster/conf.py:1032: in create_cluster
    .format(template=template))
E   ConfigurationError: No cluster template configuration by the name `test`
------------------------------------------------------- Captured log call -------------------------------------------------------
conf.py                    773 ERROR    In section `cluster/test`: Key 'nodes' error:
Wrong key u'worker' in {'master': {u'min_num': 1, u'image_id': '**not important**', u'num': 1, u'security_group': 'default', u'flavor': 'n1-standard-1', u'login': 'ubuntu'}, u'worker': {u'min_num': 4, u'image_id': '**not important**', u'num': 4, u'security_group': 'default', u'flavor': 'n1-standard-1', 'accelerator_count': '2', u'login': 'ubuntu'}}
conf.py                    777 ERROR    Dropping configuration section `cluster/test` because of the above errors
________________________________________________________ test_issue_376 _________________________________________________________
tests/test_conf.py:168: in test_issue_376
    cluster = creator.create_cluster('slurm')
elasticluster/conf.py:1032: in create_cluster
    .format(template=template))
E   ConfigurationError: No cluster template configuration by the name `slurm`
------------------------------------------------------- Captured log call -------------------------------------------------------
conf.py                    773 ERROR    In section `cluster/slurm`: Key 'nodes' error:
Key 'worker' error:
Wrong key u'boot_disk_size' in {u'min_num': 4, u'image_userdata': '', u'image_id': 'https://www.googleapis.com/compute/v1/projects/jda-labs---decision-science-01/global/images/image-python-ubuntu', u'num': 4, u'security_group': 'default', u'flavor': 'n1-standard-1', u'login': 'ubuntu', u'boot_disk_size': '20'}
conf.py                    777 ERROR    Dropping configuration section `cluster/slurm` because of the above errors
```
</details>
pointing to possibly needing similar changes elsewhere then

**Comment by riccardomurri** [comment]
Merged (with some modifications) into "master" as commit f18db64b -- many thanks for contributing this!

I ended up running the `elasticluster` command through Python's `subprocess` instead of directly invoking the main classes... I find it both easier to handle and more realistic. But all the changes are isolated in function `_run_command` so we can easily revert if we find downsides of this approach.

**Pull request closed without merging**
