### PR TITLE
Variable was not passed into include (was working prior to version 2.…

### PR DESCRIPTION
**Pull request by ewiger**
…0 of ansible). Fixed by adding support for loop control (Also see http://docs.ansible.com/ansible/playbooks_loops.html#loops-and-includes)

### CODE REVIEW

**Comment by riccardomurri** [comment]
Is this related to the infinite loop/expansion of `item` reported in #289 ?

However the docs state that:

- `loop_control` is only available in Ansible 2.1+
- `item` is the default name for the loop variable in Ansible 2.x

So it would be sufficient to just replace `include: export.yml item='{{item}}'` with `include: export.yml` ?  Otherwise we would also have to bump the dependency on Ansible to version 2.1 ...

**Comment by GlastonburyC** [comment]
Thanks for looking at this. if you could tell me when i can pull the latest version?

**Comment by riccardomurri** [comment]
I think the infinite loop is fixed in commit e4697b3 -- @ewiger can you please confirm?

**Comment by riccardomurri** [comment]
I cannot reproduce this with the latest "master" code; assuming it's fixed.

**Pull request closed without merging**
