### PR TITLE
Merge old AWS-related pull requests into recent "master"

### PR DESCRIPTION
**Pull request by riccardomurri**
This is an attempt to finally merge old pull requests by @jwm into ElastiCluster's "master" branch.

This pull request supercedes #130, #132, #133, and #139.

### CODE REVIEW

**Comment by riccardomurri** [comment]
**Note:** It's possible that the `boot_disk_*` features here create EBS volumes that are not deleted when the cluster is destroyed!  Please check and tell me if this actually happens.

**Comment by riccardomurri** [comment]
hello @monajemi , could you please check if you're hitting the same issue as https://github.com/gc3-uzh-ch/elasticluster/issues/541 ?  (specifically, resolution is in https://github.com/gc3-uzh-ch/elasticluster/issues/541#issuecomment-378039163 )

**Comment by riccardomurri** [comment]
Hmmm... no :-( I can confirm it's a separate bug -- see #548

**Comment by monajemi** [comment]
Hi @riccardomurri 
That problem is solved. But I could not get 500 GB of standard Disk. It doesn't start any volume. Is the boot_disk* tested?

```
[cluster/ec2]
...
# Ask for 500G of disk
boot_disk_type=standard
boot_disk_size=500
```

**Comment by riccardomurri** [comment]
Hi @monajemi what you may be missing is that the code supporting `boot_disk_*` is only in this pull request and not in the "master" branch -- the master branch will just *ignore* `boot_disk_*`

**Comment by monajemi** [comment]
@riccardomurri makes sense. I was using Docker image... thought this was merged. I will try building one with this branch

**Comment by riccardomurri** [comment]
@monajemi I merged into "master" anyway -- if code is broken, somebody will notice and report...

**Pull request merged**
