### PR TITLE
Honor `OS_CACERT` environment variable

### PR DESCRIPTION
**Pull request by riccardomurri**

### CODE REVIEW

**Comment by verdurin** [comment]
@riccardomurri I've applied this via `patch` and now see a different error when trying to start a cluster:
```
(elasticluster)[centos@admin2 src]$ elasticluster -vvvvv start -n iccloud-c7-10 slurm-on-centos74
2017-11-09 10:13:06 admin2.novalocal gc3.elasticluster[9672] WARNING DEBUG mode: will not issue parallel requests to cloud API.
2017-11-09 10:13:06 admin2.novalocal gc3.elasticluster[9672] DEBUG Checking section `cluster/slurm-on-centos74` ...
2017-11-09 10:13:06 admin2.novalocal gc3.elasticluster[9672] DEBUG Checking section `login/centos` ...
2017-11-09 10:13:06 admin2.novalocal gc3.elasticluster[9672] DEBUG Checking section `setup/slurm` ...
2017-11-09 10:13:06 admin2.novalocal gc3.elasticluster[9672] DEBUG Checking section `cloud/openstack` ...
2017-11-09 10:13:06 admin2.novalocal gc3.elasticluster[9672] WARNING ImportWarning: Not importing directory '/home/centos/src/elasticluster/lib/python2.7/site-packages/oslo_i18n/locale': missing __init__.py
2017-11-09 10:13:07 admin2.novalocal gc3.elasticluster[9672] DEBUG Using class <class 'elasticluster.providers.openstack.OpenStackCloudProvider'> from module <module 'elasticluster.providers.openstack' from '/home/centos/src/elasticluster/src/elasticluster/providers/openstack.pyc'> to instanciate provider 'openstack'
2017-11-09 10:13:07 admin2.novalocal gc3.elasticluster[9672] DEBUG OpenStack auth URL taken from env variable OS_AUTH_URL
2017-11-09 10:13:07 admin2.novalocal gc3.elasticluster[9672] DEBUG OpenStack cacert taken from env variable OS_CACERT
2017-11-09 10:13:07 admin2.novalocal gc3.elasticluster[9672] DEBUG OpenStack user name taken from env variable OS_USERNAME
2017-11-09 10:13:07 admin2.novalocal gc3.elasticluster[9672] WARNING FutureWarning: OpenStack user domain name is present both in the environment and the config file. Environment variable OS_USER_DOMAIN_NAME takes precedence, but this may change in the future.
2017-11-09 10:13:07 admin2.novalocal gc3.elasticluster[9672] DEBUG OpenStack password taken from env variable OS_PASSWORD
2017-11-09 10:13:07 admin2.novalocal gc3.elasticluster[9672] DEBUG OpenStack project name taken from env variable OS_PROJECT_NAME
2017-11-09 10:13:07 admin2.novalocal gc3.elasticluster[9672] DEBUG OpenStack region_name taken from env variable OS_REGION_NAME
2017-11-09 10:13:07 admin2.novalocal gc3.elasticluster[9672] DEBUG Using OpenStack Identity API v3 because of environmental variable setting `OS_IDENTITY_API_VERSION=3`
2017-11-09 10:13:07 admin2.novalocal gc3.elasticluster[9672] DEBUG Using class <class 'elasticluster.providers.ansible_provider.AnsibleSetupProvider'> from module <module 'elasticluster.providers.ansible_provider' from '/home/centos/src/elasticluster/src/elasticluster/providers/ansible_provider.pyc'> to instanciate provider 'ansible'
2017-11-09 10:13:07 admin2.novalocal gc3.elasticluster[9672] DEBUG setting variable multiuser_cluster=yes for node kind master
2017-11-09 10:13:07 admin2.novalocal gc3.elasticluster[9672] DEBUG setting variable multiuser_cluster=yes for node kind worker
Starting cluster `iccloud-c7-10` with:
* 4 worker nodes.
* 1 master nodes.
(This may take a while...)
2017-11-09 10:13:07 admin2.novalocal gc3.elasticluster[9672] ERROR Error: 'Start' object has no attribute 'parallel'
Traceback (most recent call last):
  File "/home/centos/src/elasticluster/src/elasticluster/__main__.py", line 197, in main
    return self.params.func()
  File "/home/centos/src/elasticluster/src/elasticluster/subcommands.py", line 81, in __call__
    return self.execute()
  File "/home/centos/src/elasticluster/src/elasticluster/subcommands.py", line 201, in execute
    cluster.start(min_nodes=min_nodes, parallel=self.parallel)
AttributeError: 'Start' object has no attribute 'parallel'
Aborting because of errors: 'Start' object has no attribute 'parallel'.
```

**Comment by riccardomurri** [comment]
This last error might be a problem with the current "master" branch -- can you please check out code from https://GitHub.com/riccardomurri/elasticluster branch "issues/#501" and try again?

**Comment by verdurin** [comment]
Okay, checked out that branch and manually applied the `azure`-related fixes.

This time I see what looks like a parsing error:
```
2017-11-09 18:31:37 admin2.novalocal gc3.elasticluster[26146] ERROR Could not start node `worker001`: __init__() got an unexpected keyword argument 'cacert' -- <type 'exceptions.TypeError'>
Traceback (most recent call last):
  File "/home/centos/src/elasticluster-cacert-fix/src/elasticluster/cluster.py", line 499, in _start_node
    node.start()
  File "/home/centos/src/elasticluster-cacert-fix/src/elasticluster/cluster.py", line 1141, in start
    **self.extra)
  File "/home/centos/src/elasticluster-cacert-fix/src/elasticluster/providers/openstack.py", line 414, in start_instance
    self._init_os_api()
  File "/home/centos/src/elasticluster-cacert-fix/src/elasticluster/providers/openstack.py", line 251, in _init_os_api
    cacert=self._os_cacert)
  File "/home/centos/src/elasticluster-cacert-fix/lib/python2.7/site-packages/neutronclient/v2_0/client.py", line 2265, in __init__
    super(Client, self).__init__(**kwargs)
  File "/home/centos/src/elasticluster-cacert-fix/lib/python2.7/site-packages/debtcollector/renames.py", line 43, in decorator
    return wrapped(*args, **kwargs)
  File "/home/centos/src/elasticluster-cacert-fix/lib/python2.7/site-packages/neutronclient/v2_0/client.py", line 251, in __init__
    self.httpclient = client.construct_http_client(**kwargs)
  File "/home/centos/src/elasticluster-cacert-fix/lib/python2.7/site-packages/debtcollector/renames.py", line 43, in decorator
    return wrapped(*args, **kwargs)
  File "/home/centos/src/elasticluster-cacert-fix/lib/python2.7/site-packages/debtcollector/renames.py", line 43, in decorator
    return wrapped(*args, **kwargs)
  File "/home/centos/src/elasticluster-cacert-fix/lib/python2.7/site-packages/neutronclient/client.py", line 416, in construct_http_client
    **kwargs)
TypeError: __init__() got an unexpected keyword argument 'cacert'
```

**Comment by verdurin** [comment]
The checked out tree definitely includes the fix:
```
(elasticluster-cacert-fix)[centos@admin2 src]$ git log -n 1
commit 85a777d0908dc19995a72a7f2fcb1c88ec1c44d3
Author: Riccardo Murri <riccardo.murri@gmail.com>
Date:   Wed Nov 8 10:19:08 2017 +0100

    OpenStack: Honor env var `OS_CACERT`

    Fix #501
```

**Comment by riccardomurri** [comment]
> TypeError: __init__() got an unexpected keyword argument 'cacert'

Aaaarrrrrggggghhhhhh OpenStack!!!  *All* client APIs accept a `cacert` parameter, *except* `neutronclient` where it's called `ca_cert` ...

**Comment by riccardomurri** [comment]
Commit 0ecaa24 should finally solve the problem.  Can you please try again?

**Comment by verdurin** [comment]
A `keystone` error this time, I'm afraid:
```
2017-11-11 11:02:47 admin2.novalocal gc3.elasticluster[27295] DEBUG Creating OpenStack Compute API (Nova) v2 client ...
2017-11-11 11:02:47 admin2.novalocal gc3.elasticluster[27295] DEBUG Creating OpenStack Network API (Neutron) client ...
2017-11-11 11:02:47 admin2.novalocal gc3.elasticluster[27295] DEBUG Creating OpenStack Image API (Glance) v2 client ...
2017-11-11 11:02:47 admin2.novalocal gc3.elasticluster[27295] DEBUG Creating OpenStack Volume API (Cinder) v2 client ...
2017-11-11 11:02:47 admin2.novalocal gc3.elasticluster[27295] DEBUG Checking keypair `elasticluster` ...
2017-11-11 11:02:47 admin2.novalocal gc3.elasticluster[27295] ERROR Could not start node `worker001`: SSL exception connecting to https://<API host>:5000/v3/auth/tokens: ("bad handshake: Error([('SSL routines', 'ssl3_get_s
erver_certificate', 'certificate verify failed')],)",) -- <class 'keystoneauth1.exceptions.connection.SSLError'>
Traceback (most recent call last):
  File "/home/centos/src/elasticluster-cacert-fix/src/elasticluster/cluster.py", line 499, in _start_node
    node.start()
  File "/home/centos/src/elasticluster-cacert-fix/src/elasticluster/cluster.py", line 1141, in start
    **self.extra)
  File "/home/centos/src/elasticluster-cacert-fix/src/elasticluster/providers/openstack.py", line 425, in start_instance
    self._check_keypair(key_name, public_key_path, private_key_path)
  File "/home/centos/src/elasticluster-cacert-fix/src/elasticluster/providers/openstack.py", line 594, in _check_keypair
    keypair = self.nova_client.keypairs.get(name)
  File "/home/centos/src/elasticluster-cacert-fix/lib/python2.7/site-packages/novaclient/api_versions.py", line 393, in substitution
    return methods[-1].func(obj, *args, **kwargs)
  File "/home/centos/src/elasticluster-cacert-fix/lib/python2.7/site-packages/novaclient/v2/keypairs.py", line 74, in get
    "keypair")
  File "/home/centos/src/elasticluster-cacert-fix/lib/python2.7/site-packages/novaclient/base.py", line 351, in _get
    resp, body = self.api.client.get(url)
  File "/home/centos/src/elasticluster-cacert-fix/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 304, in get
    return self.request(url, 'GET', **kwargs)
  File "/home/centos/src/elasticluster-cacert-fix/lib/python2.7/site-packages/novaclient/client.py", line 77, in request
    **kwargs)
  File "/home/centos/src/elasticluster-cacert-fix/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 463, in request
    resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
  File "/home/centos/src/elasticluster-cacert-fix/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 189, in request
    return self.session.request(url, method, **kwargs)
  File "/home/centos/src/elasticluster-cacert-fix/lib/python2.7/site-packages/keystoneauth1/session.py", line 573, in request
    auth_headers = self.get_auth_headers(auth)
  File "/home/centos/src/elasticluster-cacert-fix/lib/python2.7/site-packages/keystoneauth1/session.py", line 900, in get_auth_headers
    return auth.get_headers(self, **kwargs)
  File "/home/centos/src/elasticluster-cacert-fix/lib/python2.7/site-packages/keystoneauth1/plugin.py", line 90, in get_headers
    token = self.get_token(session)
  File "/home/centos/src/elasticluster-cacert-fix/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 89, in get_token
    return self.get_access(session).auth_token
  File "/home/centos/src/elasticluster-cacert-fix/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 135, in get_access
    self.auth_ref = self.get_auth_ref(session)
  File "/home/centos/src/elasticluster-cacert-fix/lib/python2.7/site-packages/keystoneauth1/identity/v3/base.py", line 165, in get_auth_ref
    authenticated=False, log=False, **rkwargs)
  File "/home/centos/src/elasticluster-cacert-fix/lib/python2.7/site-packages/keystoneauth1/session.py", line 848, in post
    return self.request(url, 'POST', **kwargs)
  File "/home/centos/src/elasticluster-cacert-fix/lib/python2.7/site-packages/keystoneauth1/session.py", line 698, in request
    resp = send(**kwargs)
  File "/home/centos/src/elasticluster-cacert-fix/lib/python2.7/site-packages/keystoneauth1/session.py", line 760, in _send_request
    raise exceptions.SSLError(msg)
SSLError: SSL exception connecting to https://<API host>:5000/v3/auth/tokens: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
```

**Comment by riccardomurri** [comment]
Is there any public endpoint against which I can test a connection? (No
need for credentials, just checking if SSL negotiations succeed.). All the
OpenStack clouds that I have access to do have SSL certificates from
well-known CAs so no need for separate CA PEM files...

**Comment by verdurin** [comment]
Someone else has given me access to this cloud, so I've asked him if this is okay.

**Comment by verdurin** [comment]
@riccardomurri - he said it's okay to give you the URL privately. What's the best method to get this over to you?

**Comment by riccardomurri** [comment]
Email me or private message on the ElastiCluster chat: http://gitter.im/elasticluster/chat

**Comment by verdurin** [comment]
Sent via Gitter.

**Comment by verdurin** [comment]
@riccardomurri - any progress on this? Let me know if you need any more from my end.

**Comment by riccardomurri** [comment]
@verdurin Sorry, have been very busy rebuilding a storage cluster here.  I should have more time in the next couple of weeks, after the new storage cluster has proved itself stable...

**Pull request merged**
